explore with me
Seetochka/java-explore-with-me pull request #1
Opened 2022-09-21 19:02 UTC by Seetochka

2022-09-22 08:53 UTC, eugene-lenkevich requested changes
Привет, Светлана, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошла до дипломной работы, это очень здорово, ты молодец, и, вообще, очень нравится скурпулезность при выполнении работ :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, я оставил кучку коментариев. 
В первую очередь а) сборка должна собираться (она собирается, тут гут) и, соответственно, б) должны проходить автотесты в гитхабе. 

Надо сделать конфетку, возможно, потом, кто то, и, возможно, будущий работодатель, будет смотреть эту работу и на него надо произвести впечатление, штаны через голову одевать не надо, но базовые вещи должны быть в порядке :) 
В общем, будут вопросы, задавай в слаке, не стесняйся, проект совсем немножко допилить осталось :)

Удачи!

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +    public EventClient(@Value("${stats-service.url}") String serverUrl, RestTemplateBuilder builder) {
Инициализация объекта происходит через конструктор, в принципе в этом нет ничего особенного, но предложу еще вариант. 
Можно создать специальный класс конфигурации
@Configuration
public class WebClientConfiguration {
 public EventClient  eventClient (/тут зависимости/) {
//тут создание бина
}
} 

так мы вынесем ответственность по инициализации бина вовне, архитектурно более правильно, но не критично
Примеры вот тут
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html

![image](https://user-images.githubusercontent.com/94845100/191687820-0344a257-398d-4aa2-9a5c-a4133adaaaf0.png)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +        String start = LocalDateTime.now().minusDays(10L).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
"yyyy-MM-dd HH:mm:ss"

Это лучше в константу вынести, несколько раз встречается :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +                .map(object -> (new ObjectMapper()).convertValue(object, ViewStats.class))
А может лучше объект создать один раз и просто потом его инжектить?
Можно кстати так же создать конфигурацию, иногда его бывает надо настроить, может быть удобно

new ObjectMapper()

И снова примерчик, только у тебя тривиально будет, без настроек
 
![image](https://user-images.githubusercontent.com/94845100/191689775-0fe381f8-6bd8-43bc-94f1-cf86507c6f84.png)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/AdminUpdateEventRequestDto.java
> +        private Float lat;
Вот как раз тут стоит добавить описание что это, это специфика предметной области, просто пара строчек про то какие это координаты :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/EndpointHitDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Этот формат даты указывается много раз, стоит его вынести в константы чтобы было только одно место где он задается :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/EventFullDto.java
> + * DTO события
У нас уже есть одно "DTO события" :) 
Подобный коментарий, кстати, особо то и не несет смысла, в принципе, из имени класса все понятно, но пусть будет, но можно особо не заморачиваться и не коментировать подобное :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/UpdateEventRequestDto.java
> + * DTO события
А вот тут коментарий не особо согласуется с кодом, судя по имени класса, потому с коментариями надо аккуратно :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/exceptions/LoggingException.java
> +        log.error("{}. {}", className, message);
А нет ли тут переусложнения, во первых нужна ли такая развесистая иерархия исключений, а во вторых, не лучще ли логированием ошибок заниматься в обработчике ошибок, а не тут, все таки несвойственная для исключения обязанность, обычно композиция лучше чем наследование :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/models/Category.java
> +public class Category {
Для entity не хватает equals и hashCode
Причем вычисляться они должны по идентификатору. Потому что это не просто объекты, а представление конкретной строки в таблице базы данных, то есть два (или более) объекта формально могут отличаться полями(кроме id), но быть одной и той же записью в таблице, просто разные версии. Этот момент надо иметь в виду :)

А вот как разруливается наличие разных версий - это отдельная обширная тема, выходящая за программу курса
https://habr.com/ru/post/268903/

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/services/impl/CategoryServiceImpl.java
> +    public Category create(Category category) {
Над подобными методами лучше ставить @Transactional
Такие операции как создание, обновление и удаление стоит выполнять в рамках логической транзакции, так мы убережем нашу базу от частично обновленных записей, допустим при обновлении мы делаем изменения в трех таблицах и на третей получили ошибку - откатить мы должны все, этьо и есть логическая транзакция. Хотя да, наши методы тривиальны, но тем не менее :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/services/impl/CategoryServiceImpl.java
> +    public boolean checkExistsById(long id) {
Чет с трудом понимаю что делает метод, но проверяет то что записть не существует?
Может лучше назвать checkIfNotExists или как то так :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/services/impl/CompilationServiceImpl.java
> +        if (checkExistsById(id)) {
Метод определенно надо переименовать, он проверяет то что запись НЕ существует, я бы подумал наоборот :)

2022-09-22 08:53 UTC, eugene-lenkevich commented on ewm-service/src/test/java/ru/practicum/statsservice/EwmServiceApplicationTests.java
> +class EwmServiceApplicationTests {
В этой работе тесты не требуют, но если получится то будет очень кстати. А этот лучше немножко доработать, сделать из него smoke test, но если получится и время будет :)

https://github.com/spring-guides/gs-testing-web/blob/main/complete/src/test/java/com/example/testingweb/SmokeTest.java

2022-09-25 16:02 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +    public EventClient(@Value("${stats-service.url}") String serverUrl, RestTemplateBuilder builder) {
Попробовала реализовать, насколько правильно не уверена, но работает

2022-09-25 16:02 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +        String start = LocalDateTime.now().minusDays(10L).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
Вынесла

2022-09-25 16:03 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +                .map(object -> (new ObjectMapper()).convertValue(object, ViewStats.class))
Также сделала конфигурацию

2022-09-25 16:03 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/AdminUpdateEventRequestDto.java
> +        private Float lat;
Добавила

2022-09-25 16:03 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/EndpointHitDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Вынесла, но не уверена можно ли так

2022-09-25 16:04 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/EventFullDto.java
> + * DTO события
Поправила комментарии

2022-09-25 16:04 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/exceptions/LoggingException.java
> +        log.error("{}. {}", className, message);
Вынесла логи в обработчик ошибок

2022-09-25 16:04 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/models/Category.java
> +public class Category {
Добавила

2022-09-25 16:04 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/services/impl/CategoryServiceImpl.java
> +    public Category create(Category category) {
Добавила

2022-09-25 16:05 UTC, Seetochka commented on ewm-service/src/main/java/ru/practicum/ewmservice/services/impl/CategoryServiceImpl.java
> +    public boolean checkExistsById(long id) {
Сделала логику метода по названию

2022-09-26 04:46 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/clients/EventClient.java
> +    public EventClient(@Value("${stats-service.url}") String serverUrl, RestTemplateBuilder builder) {
Да, именно так, все верно :)

Такой подход, кстати, позволяет легко конфигурировать приложение, в зависимости от параметров запуска мы может подтягиваться нудная кофигурация вэб-клиента. Например для прода с ssl и пр, для тестового стенда простой клиент, а для тестов вообще заглушка которая будет возвращать статический ответ.

Вот статья на английском, но зато кратко и по делу 
https://www.baeldung.com/spring-profiles

2022-09-26 04:50 UTC, eugene-lenkevich commented on ewm-service/src/main/java/ru/practicum/ewmservice/dto/EndpointHitDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
Вообще, по идее это решается конфигурированием сериализатора, что, в принципе, ты  и делаешь в кофнигурации. Можно попробовать убрать эти аннотации с самих dto и посмотреть что будет

![image](https://user-images.githubusercontent.com/94845100/192195997-00069dc2-f99e-43b3-9991-7c79f3d9125c.png)

https://www.baeldung.com/spring-boot-formatting-json-dates

2022-09-26 05:03 UTC, eugene-lenkevich approved these changes
Привет, Светлана, спасибо за исправления, можно конечно к чему нибудь придраться, к именам пакетов во множественном числе (clients, configurations и пр), но я думаю что в целом достаточно, к тому же до идеала нет смысла доводить, это бессмысленно так как субъективно и на реальных проектах все бывает немного по разному :)
Я аппрув поставлю, но ты можешь еще, если время будет, посмотреть форматирование дат. По идее с dto форматы можно снять, но настроить(проверить текущую настрйоку) соответсвующим образом jackson objectMapper, т.е. сериализатор.

А в целом, ты большя молодчина, так держать, приятно проверять твои работы))

2024-01-15 14:16 UTC, merged